version: "3"

services:
  database:
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/create_tables.sql

  library-app:
    build:
      context: ./
      dockerfile: ./src/main/docker/Dockerfile
    depends_on:
      - database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DATASOURCE_PASSWORD_DRIVER_CLASS_NAME=org.postgresql.Driver
    ports:
      - "8080:8080"